version: "3.6"

services:
  app:
    image: ${REGISTRY:-local}/votingapp:${TAG:-latest}
    build:
      context: ${BUILD_CONTEXT:-.}
      dockerfile: ${VOTINGAPP_API}/Dockerfile
      args:
        api: ${VOTINGAPP_API}
        domain: ${VOTINGAPP_DOMAIN}
        tests: ${VOTINGAPP_TESTS}
        entrypoint: ${VOTINGAPP_ENTRYPOINT}
    container_name: votingapp
    ports:
      - 80:80