version: "3.3"

services:
  api:
    image: aspnetcore-debug
    build:
      context: .
      dockerfile: docker/aspnetcore-debug/Dockerfile
    container_name: votingapp-debug
    volumes: 
      - ${VOTINGAPP_API}/bin/build/:/app
    ports:
      - 80:80