version: "3.4"

services:
  commands:
    image: ${REGISTRY}/votingapp-commands:${TAG}
    build:
      context: .
      dockerfile: ${VOTINGAPP_COMMANDS}Dockerfile
      args:
        api: ${VOTINGAPP_COMMANDS}
        domain: ${VOTINGAPP_DOMAIN}
        tests: ${VOTINGAPP_TESTS}

  queries:
    image: ${REGISTRY}/votingapp-queries:${TAG}
    build:
      context: .
      dockerfile: ${VOTINGAPP_QUERIES}Dockerfile
      args:
        api: ${VOTINGAPP_QUERIES}
        domain: ${VOTINGAPP_DOMAIN}
        tests: ${VOTINGAPP_TESTS}

  gateway:
    image: ${REGISTRY}/votingapp-gateway:${TAG}
    build:
      context: .
      dockerfile: ${VOTINGAPP_GATEWAY}/Dockerfile
      args:
        api: ${VOTINGAPP_GATEWAY}
        static: ${VOTINGAPP_UI}

  integration-tests:
    image: ${REGISTRY}/integration-tests:${TAG}
    build:
      context: .
      dockerfile: ${VOTINGAPP_INTEGRATION_TESTS}Dockerfile
      args:
        tests: ${VOTINGAPP_INTEGRATION_TESTS}