version: "3.4"

services:
  votingapi:
    image: microsoft/aspnetcore
    ports:
      - 80:80
    volumes:
      - ../build/:/app
    working_dir: /app
    container_name: votingapp
    command: dotnet ./VotingApp.Api.dll