
version: "3.1"

services:
 main:
  image: paulopez/jenkins:latest
  ports:
   - 8080:8080
   - 50000:50000
  environment:
   - JENKINS_OPTS="--prefix=/jenkins"
  secrets:
   - jenkins-user
   - jenkins-pass
  volumes:
   - jm:/var/jenkins_home
   - jm_share:/usr/share/jenkins/ref
secrets:
  jenkins-user:
    external: true
  jenkins-pass:
    external: true
volumes:
  jm:
    driver: cloudstor:azure
    driver_opts:
      size: 25
    external: false
  jm_share:
    driver: cloudstor:azure
    driver_opts:
      size: 10
    external: false